import "./globals.css";
import SvgSprite from "@/components/SvgSprite";
import { headers } from 'next/headers';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function ConditionalStylesheets() {
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || '';
  const isAdminRoute = pathname.startsWith('/admin');
  
  if (isAdminRoute) {
    return null;
  }

  return (
    <>
      <link 
        rel="stylesheet" 
        href="/styles/desktop.css" 
        media="(min-width: 769px)"
      />
      <link 
        rel="stylesheet" 
        href="/styles/mobile.css" 
        media="(max-width: 768px)"
      />
      <link 
        rel="stylesheet" 
        href="/styles/components.css"
      />
    </>
  );
}

export default async function RootLayout({ children }) {
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || '';
  const isAdminRoute = pathname.startsWith('/admin');

  const bodyProps = isAdminRoute 
    ? { className: "admin-body" }
    : {
        "data-locale": "ar",
        "data-messenger": "[]", 
        "data-fb-app-id": "184540408224804",
        className: " body-fixed-header event-index-index modern-css is_rtl",
        style: { paddingTop: "119px" }
      };

  return (
    <html lang="en">
      <head>
        <ConditionalStylesheets />
      </head>
      <body {...bodyProps}>
        <SvgSprite />
        {children}
      </body>
    </html>
  );
}
